/* Some of the below code was generated by default from Unity when inserting a MonoBehavior Script. 
For a full list of sources please see the attached README. Prominent sources that were referenced will 
be listed here for convenience but it will not be an exhaustive list.*/

using UnityEngine;

public class OpenCave : MonoBehaviour
{
    public int pedestalsCorrect;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {

    }

    // Update is called once per frame
    // Relevant Source: https://docs.unity3d.com/ScriptReference/GameObject.SetActive.html and https://docs.unity3d.com/Manual/class-GameObject.html
    void Update()
    {
        if (pedestalsCorrect == 5)
            gameObject.SetActive(false);
    }
}
