/* Parts of the following script was partially generated by the Unity program by deafult when you create a script. It was adapted to meet our team's project goals. 
Some relevant sources have been placed in comments below, but this is not meant to be an exhaustive list. 
Please see the README for a full list of citations. */

/* This script is based on/adapts/references/interacts with timer_script.cs by Brian Swanson. See that script for additional citations.
Accessed: August 3, 2025. 
Scope of adaptation: I wanted to make the names similar so they would  make sense, and it has to pull the script as a component to alter on an event.

This script also functions based off of Larisa's interaction script as a trigger.
Please see the attached game object and Larisa's IInteractable.cs, InteractableObject.cs, and Interaction.cs for additional cites or details as to how that script works. */

using UnityEngine;

public class Continue : MonoBehaviour
{

    /* Relevant Sources: https://docs.unity3d.com/ScriptReference/GameObject.html
    https://docs.unity3d.com/Manual/class-GameObject.html
    https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
    The below two lines were adapted from/made after learning from these sources and possibly others. Please see the sources cited for more details.
    */
    public GameObject timerScriptObject;
    public timer_script timerScriptComponent;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        /* Relevant Sources: https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
        https://docs.unity3d.com/Manual/class-GameObject.html
        The below lines were adapted from/made after learning from these sources and possibly others. Please see the README for a full list of citations.*/
        timerScriptObject = GameObject.Find("PlayerUI");
        timerScriptComponent = timerScriptObject.GetComponent<timer_script>();      
    }

    // Update is called once per frame
    void Update()
    {
        /* Relevant source: https://learn.microsoft.com/en-au/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types (Adapted from this.)
        https://docs.unity3d.com/Manual/class-GameObject.html
        Script attributes below are based on timer_script.cs by Brian Swanson. See that script for additional citations. 
        Accessed: August 3, 2025. 
        Scope of use: Just interacting with Brian's scripts to alter variables that will let the timer continue.  
        See README for full list of sources cited. */

        if (timerScriptComponent.timesUp == true)
        {
            timerScriptComponent.timesUp = false;
        }

    }

}
