// Some of the below code was generated by default from Unity when inserting a MonoBehavior Script. 
/* For a full list of sources please see the attached README. In this file the main sources that
 were used were the ones from the Unity documentation like source #35 and the Microsoft C# reference.*/

using UnityEngine;

public class OpenCave : MonoBehaviour
{
    public bool used_pickaxe;
    public bool used_axe;
    public bool used_hammer;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        if (used_pickaxe == true)
        {
            if (used_axe == true)
            {
                if (used_hammer == true)
                {
                    Destroy(gameObject);
                    Debug.Log("Cave has opened.");
                 
                }
            }
        }
    }


// Crafted by adapating the script from source #35. See README for full list of citations and sources. 

    void OnMouseDown ()
    {
        // Used just until we can get the scene set up in such a way that it will track these variables and open on its own.
        used_pickaxe = true;
        used_axe = true;
        used_hammer = true;
        Debug.Log("Vars set");
    }




}
