/* The following code was partially generated by Unity by default when making a script. 
I have adapted that code to make this script. Please see the attached README for a full list 
of sources cited. */ 


using UnityEngine;

public class PlayerFlags : MonoBehaviour
{
    // Creating several boolean variables that pertain to the players status to trigger events
    public bool has_pickaxe;
    public bool has_used_pickaxe;
    public bool has_axe;
    public bool has_used_axe;
    public bool has_bucket; 
    public bool has_flashlight;
    public bool has_pillow;
    public bool has_sleeping_bag;
    public bool has_water;
    public bool campfire_out;
    

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
