/* The following code was partially generated by Unity by default when making a script. 
I have adapted that code to make this script. Please see the attached README for a full list 
of sources cited. */ 


using UnityEngine;

public class PlayerFlags : MonoBehaviour
{
    // Creating several boolean variables that pertain to the players status to trigger events
    public bool has_pickaxe;
    public bool has_used_pickaxe;
    public bool has_axe;
    public bool has_used_axe;
    public bool has_bucket; 
    public bool has_flashlight;
    public bool has_pillow;
    public bool has_sleeping_bag;
    public bool has_water;
    public bool campfire_out;

    // Creating several game objects to eventually get components from
    // Relevant source: https://docs.unity3d.com/Manual/class-GameObject.html
    public GameObject pickaxe;
    public GameObject axe;
    public GameObject rock;
    public GameObject tree;
    public GameObject sleeping_bag;
    public GameObject bucket;
    public GameObject flashlight;
    public GameObject pillow;
    public GameObject water;
    public GameObject campfire;
    

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
         //Getting components for several different objects.
         // Relevant source: https://docs.unity3d.com/Manual/class-GameObject.html

         pickaxe = GameObject.Find("Pickaxe");
         axe = GameObject.Find("Axe");
         rock = GameObject.Find("MineableRock");
         tree = GameObject.Find("FallableTree");
         sleeping_bag = GameObject.Find("FoldedSleepingBag");
         bucket = GameObject.Find("PlayerBucket");
         flashlight = GameObject.Find("PlayerFlashlight");
         pillow = GameObject.Find("PlayerPillow");
         water = GameObject.Find("Water");
         campfire = GameObject.Find("CampfireLight");    
    }

    // Update is called once per frame
    void Update()
    {
        /* Adding in updates to all of these so when the scripts that are attached to them
        are executed they update the values here. 
        Relevant Sources: 
        https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
        https://docs.unity3d.com/Manual/class-GameObject.html
        */
        
        has_pickaxe = pickaxe.GetComponent<ToolPickupScript>().has_used;
        has_used_pickaxe = rock.GetComponent<BreakRocks>().has_broken;
        has_sleeping_bag = sleeping_bag.GetComponent<PermPickupScript>().has_picked_up;
        // has_axe = axe.GetComponent<ToolPickupScript>().has_used;
        // has_used_axe = tree.GetComponent<TreeChopScript>().has_fallen;
        // has_pillow = pillo

    }
}
