/* Some of the code below was generated by Unity by default when creating a script. 
I have adapted it to server the purpose of our project based on information and instruction
from the sources in the README. Please review it for a list of sources cited.
*/

using UnityEngine;

public class ToolPickupScript : MonoBehaviour
{
    public GameObject player_stats;
    public bool has_used;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        /* On keypress update the players relevant attribute.
        Relevant Sources: 
        https://docs.unity3d.com/ScriptReference/Object.Destroy.html
        https://docs.unity3d.com/ScriptReference/KeyCode.html
        https://docs.unity3d.com/ScriptReference/Input.html
        See README for full list of sources. 
        */
        if(Input.GetKeyDown(KeyCode.E)){
            Destroy(gameObject);
            has_used = true;
        }
    }
}
