// The below code was adapted from what was generated by default by the Unity Engine when inserting a Monobehavior script. 
// Please see the sources cited in the attached README for a full list of sources cited.

using UnityEngine;

    /*Some of the below code was by default provided by the Unity engine. 
    The below code is based on the sources in the README, especially    
    sources 34,35,37,38,45,46,etc. Please see the README for a full list of sources. */

    /*This code was inspired directly from several sources in the readme expecially the following sources #35 and #46:
    35. Unity Technologies. (2025). *Unity Documentation, MonoBehavior.OnMouseDown().* Unity Technologies. 
    https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseDown.html Accessed: July 2025. 

    46.Unity Technologies. (2025, July 25). *Unity Documentation, Animation.* 
    Unity Technologies. https://docs.unity3d.com/ScriptReference/Animation.html Accessed: July 2025. */

public class TreeChopScript : MonoBehaviour
{

    public GameObject treeInteractBox = GameObject.Find("treeInteractBox");
    public GameObject treeChopCollider = GameObject.Find("TreeChopCollider");
    public GameObject axe = GameObject.Find("Axe");
    Animator treeAnimator = fallableTree.GetComponent<Animator>();
    public bool treeChoppable = false;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame

    /*
    The code below was developed based on several different sources. Here are a few of the more relevant ones:



    Also see the sources in the README and at mentioned at the top of the page.
    */
    void Update()
    {

    }

}
