// The below code was adapted from what was generated by default by the Unity Engine when inserting a Monobehavior script. 
// Please see the sources cited in the attached README for a full list of sources cited.

using UnityEngine;

    /*Some of the below code was by default provided by the Unity engine. 
    The below code is based on/adapted from the sources in the README, especially:    
    https://docs.unity3d.com/Manual/class-GameObject.html
    https://docs.unity3d.com/ScriptReference/GameObject.html
    https://docs.unity3d.com/6000.1/Documentation/ScriptReference/Animator.html
    https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
    Please see the README for a full list of sources. */
    

public class TreeChopScript : MonoBehaviour
{

    public GameObject treeInteractBox = GameObject.Find("treeInteractBox");
    public GameObject treeChopCollider = GameObject.Find("TreeChopCollider");
    public GameObject axe = GameObject.Find("Axe");
    Animator treeAnimator = GetComponent<Animator>();
    public bool treeChoppable = false;
    //public GameObject collidingObject;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame

    /*
    The code below was developed based on several different sources. Here are a few of the more relevant ones:



    Also see the sources in the README and at mentioned at the top of the page.
    */
    /* Accessed July 29 2025
    Adapted from the following source to fit collisions with our axe object:
    JD Dev, https://www.youtube.com/watch?v=vQY4jsho1nQ
    See sources cited for full cite, it is citation #1. 
    
    Also based on these sources: 
    https://docs.unity3d.com/ScriptReference/Collider.html
    https://docs.unity3d.com/Manual/class-GameObject.html
    */

    void Update()
    {
  
    }

    void OnCollisionEnter(Collider collidingObject)
    {
        if (collidingObject == axe){
            Debug.Log("The axe is in the right spot.");


        }
    }

    void OnCollisionExit()
    {
        Debug.Log("Axe left.");


    }




}
