/* Portions of this script were auto generated by Unity, and I have adapted them to fit our project. 
Here are some of the sources that were adapted to create this script.
https://docs.unity3d.com/ScriptReference/Collider.OnCollisionEnter.html
https://docs.unity3d.com/ScriptReference/Collider.OnCollisionExit.html
https://docs.unity3d.com/ScriptReference/Collider.OnTriggerExit.html
https://docs.unity3d.com/ScriptReference/Collider.OnTriggerEnter.html
https://docs.unity3d.com/Manual/class-GameObject.html
https://www.youtube.com/watch?v=vQY4jsho1nQ
https://www.youtube.com/watch?v=K0Sj4Al-l0w
Accessed June - July 2025.

Please see the README for a full list of citation. */


using UnityEngine;

public class TreeColliderScript : MonoBehaviour
{
    private GameObject fallableTree;
    public TreeChopScript treeScript;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        fallableTree = GameObject.Find("FallableTree");
        treeScript = fallableTree.GetComponent<TreeChopScript>();
    }

    // Detects if axe enters the collider
    void OnTriggerEnter(Collider objectCollider)
    {
        if (objectCollider.gameObject == treeScript.axe)
        {
            treeScript.treeChoppable = true;
        }


    }

    // Detects if axe leaves the collider
    void OnTriggerExit(Collider objectCollider)
    {
        if (objectCollider.gameObject == treeScript.axe)
        {
            treeScript.treeChoppable = false;

        }

    }
}
