/* This script contains code below that is default generated by Unity. Our team adapted this code to fit our project. 
Some sources will be present in links below for convenience. This is not an exhaustive list. See the README for a full list of sources.

This file is meant to be a replacement/retrofitted version of the original player flags file. It will server a similar purpose but with 
a much smaller scope. Instead of tracking a large group of events, it will only track puzzle completion and activate the final exit object.
*/

using UnityEngine;

public class FinalExit : MonoBehaviour
{
    /* Relevant Sources: https://docs.unity3d.com/Manual/class-GameObject.html 
    https://docs.unity3d.com/ScriptReference/GameObject.html
    https://docs.unity3d.com/ScriptReference/Component.html
    https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
    Developed from and adapted from these sources. Please see the README for a full list of citations.
    */
    public GameObject finalExit;
    public GameObject bedRoll;
    public GameObject playerPillow;
    public GameObject campfireOutObject;
    public PuzzleFinish bedRollScript;
    public PuzzleFinish playerPillowScript;
    public PuzzleFinish campfireOutScript;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        /* Relevant Sources: https://docs.unity3d.com/Manual/class-GameObject.html 
        https://docs.unity3d.com/ScriptReference/Component.html
        https://docs.unity3d.com/ScriptReference/Component.GetComponent.html
        The following block of code is adapted from these sources. Please see the README for a full list of citations.
        */
        bedRollScript = bedRoll.GetComponent<PuzzleFinish>();
        playerPillowScript = playerPillow.GetComponent<PuzzleFinish>();
        campfireOutScript = campfireOutObject.GetComponent<PuzzleFinish>();
    }

    // Update is called once per frame
    void Update()
    {
        /*
        Relevant Sources: 
        https://docs.unity3d.com/Manual/class-GameObject.html (Adapted to create the code below).
        https://learn.microsoft.com/en-au/dotnet/csharp/language-reference/operators/boolean-logical-operators
        The below code is adapted from these sources. Please see sources cited in the README for a full list of citations.
        */
        if (bedRollScript.isCompleted == true && playerPillowScript.isCompleted == true)
        {
            if (campfireOutScript.isCompleted == true && finalExit.activeSelf == false)
            {
            finalExit.SetActive(true);
            }
        }
    }
}
