/* This script contains code below that is default generated by Unity. Our team adapted this code to fit our project. 
Some sources will be present in links below for convenience. This is not an exhaustive list. See the README for a full list of sources.

This file is meant to be a replacement/retrofitted version of the original player flags file. It will server a similar purpose but with 
a much smaller scope. Instead of tracking a large group of events, it will only track puzzle completion and activate the final exit object.
*/

using UnityEngine;

public class FinalExit : MonoBehaviour
{
    // Relevant Source: https://learn.microsoft.com/en-au/dotnet/csharp/language-reference/builtin-types/bool
    public bool hasPillow;
    public bool hasSleepingBag;
    public bool campfireOut;

    //Relevant Sources: https://docs.unity3d.com/Manual/class-GameObject.html and https://docs.unity3d.com/ScriptReference/GameObject.html
    public GameObject finalExit;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        // Relevant Source: https://docs.unity3d.com/Manual/class-GameObject.html (Adapted to create the line below).
        finalExit = GameObject.Find("FinalExit");
    }

    // Update is called once per frame
    void Update()
    {
        /*
        Relevant Sources: 
        https://docs.unity3d.com/Manual/class-GameObject.html (Adapted to create the code below).
        https://learn.microsoft.com/en-au/dotnet/csharp/language-reference/operators/boolean-logical-operators
        See sources cited for a full list of citations.
        */
        if (hasPillow == true && hasSleepingBag == true)
        {
            if (campfireOut == true && finalExit.activeSelf == false)
            {
            finalExit.SetActive(true);
            }
        }
    }
}
